### ISSUE TITLE
Add ability to get Job Salary

### ISSUE THREAD

**Issue by BillWCJ** [BillWCJ/JobSearcher#3]
Get relevant Job salary information from the web.

Suggested site for information: 
RateMyCoop and maybe Glassdoor or PayScale

Simple Requirement Breakdown:
[x] Add new salary class In Model.Entity
[x] Add associated relationship for database and querying methods in Data.EF.Cluster
[x] Implement Web search on websites and extra information in Data.Web.{websitename}

**Comment by BillWCJ** [comment]
Done, Thanks to Paul

**Comment by psoladoye** [comment]
Have you merged my branch into develop?

**Comment by BillWCJ** [comment]
Yes I believe I did. I think you should branch off of dev from now on. How's England

--- Original Message ---

**Comment by psoladoye** [comment]
Leaving by 10:15 pm today. Should be fun

**Comment by BillWCJ** [comment]
Omg, have fun in England!

--- Original Message ---
